[project]
name = "grafanaut"
version = "0.1.0"
description = "Modulares Backup- und Restore-Tool für Grafana via REST API"
authors = [
    { name = "Nils Holthues", email = "nils.holthues@akra.de" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
    "PyYAML>=6.0.1",
    "python-dotenv>=1.0.1"
]

[project.scripts]
grafanaut = "grafanaut.__main__:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["grafanaut"]
